### ISSUE TITLE
Prefer Fish events definitions on paket.toml

### ISSUE THREAD

**Issue by joseluisq** [joseluisq/paket#8]
It would great if we can define custom Fish shell event names (`--on-event`) via the `paket.toml` file for the Paket events. 

__Proposal__

```toml
# ....

[events]
after-install = "gitnow_install"
after-update = "gitnow_update"
before-uninstall = "gitnow_uninstall"
```

__Fish event name nomenclature__

`PACKAGE-NAME_EVENT-NAME`

For example:

```toml
[events]
after-install = "gitnow_install"
# Dividing the package and the Fish event name with an underscore (_)
```

The `[events]` section defines the Paket events and the values the [Fish event names](https://fishshell.com/docs/current/cmds/emit.html) of a package which Paket will emit.
